FROM almalinux:8

RUN dnf install -y openssh-server && \
    dnf clean all

RUN ssh-keygen -A && \
    useradd -m testuser && \
    echo 'testuser:test1234!' | chpasswd && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]