FROM opensuse/leap:15.5

RUN zypper install -y openssh && \
    zypper clean

RUN ssh-keygen -A && \
    useradd -m testuser && \
    echo 'testuser:test1234!' | chpasswd && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]