
services:

  # ------- RHEL 계열 ------
  centos7:
    build:
      context: .
      dockerfile: Dockerfile.centos7
    container_name: ssh-centos7
    ports:
      - "2221:22"
  
  centos5:
    build: 
      context: .
      dockerfile: Dockerfile.centos5
    container_name: ssh-centos5
    hostname: centos5
    ports:
      - "2220:22"

  alma8:
    build:
      context: .
      dockerfile: Dockerfile.alma8
    container_name: ssh-alma8
    hostname: alma8
    ports:
      - "2222:22"

  alma9:
    build:
      context: .
      dockerfile: Dockerfile.alma9
    container_name: ssh-alma9
    hostname: alma9
    ports:
      - "2223:22"

  rhe18:
    build:
      context: .
      dockerfile: Dockerfile.rhel8
    container_name: ssh-rhel8
    hostname: rhe18
    ports:
      - "2224:22"

  rhe19:
    build:
      context: .
      dockerfile: Dockerfile.rhel9
    container_name: ssh-rhel9
    hostname: rhe19
    ports:
      - "2225:22"
  
  rocky8:
    build: 
      context: . 
      dockerfile: Dockerfile.rocky8
    container_name: ssh-rocky8
    hostname: rocky8
    ports:
      - "2226:22"
  
  rocky9:
    build:
      context: .
      dockerfile: Dockerfile.rocky9
    container_name: ssh-rocky9
    hostname: rocky9
    ports:
      - "2227:22"
  
  sles15:
    build:
      context: .
      dockerfile: Dockerfile.s1es15
    container_name: ssh-sles15
    hostname: sles15
    ports:
      - "2228:22"
  

  ubuntu2004:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2004
    container_name: ssh-ubuntu2004
    hostname: ubuntu2004
    ports:
      - "2229:22"

  # !! jsch 실패 케이스
  ubuntu2204:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2204
    container_name: ssh-ubuntu2204
    hostname: ubuntu2204
    ports:
      - "2230:22"

  ubuntu2404:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu2404
    container_name: ssh-ubuntu2404
    hostname: ubuntu2404
    ports:
      - "2231:22"






  
  